apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: images.my-company.example/app:v4
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"
  - name: log-aggregator
    image: images.my-company.example/log-aggregator:v6
    resources:
      requests:
        ephemeral-storage: "2Gi"
      limits:
        ephemeral-storage: "4Gi"
    volumeMounts:
    - name: ephemeral
      mountPath: "/tmp"
    startupProbe:
        exec:
            command:
            - ls
            - /tmp/healthy
        initialDelaySeconds: 10
        periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 8080
    readinessProbe:
        httpGet:
            path: /ready
            port: 8080
  volumes:
    - name: ephemeral
      emptyDir:
        sizeLimit: 500Mi