apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # 与PV中的storageClassName一致
  resources:
    requests:
      storage: 2Gi
